In [2]:
'''
    矩阵乘法 np.dot()
'''
import numpy as np

X=[1,2]
state = [0.0, 0.0]

# 定义循环体内的全连接神经网络的权重weight和偏置项bias
# 因为rnn中状态向量和输入向量是拼接到一起的，所以它们各自的权重也分开定义
w_cell_state = np.asarray([[0.1, 0.2], [0.3, 0.4]])
w_cell_input = np.asarray([0.5, 0.6])
b_cell = np.asarray([0.1, -0.1])

# 定义输出的全连接网络的参数
w_output = np.asarray([[1.0], [2.0]])
b_output = 0.1

# 按时间顺序执行循环神经网络的向前传播过程
for i in range(len(X)):
    # 计算循环体中的全连接层神经网络
    before_activation = np.dot(state, w_cell_state) + X[i] * w_cell_input + b_cell
    state = np.tanh(before_activation)
    
    # 根据当前时刻状态计算最终输出
    final_output = np.dot(state, w_output) + b_output
    
    # 输出每个时刻的信息
    print("before_activation:", before_activation)
    print("state：",state)
    print("final_output",final_output)

before_activation: [0.6 0.5]
state： [0.53704957 0.46211716]
final_output [1.56128388]
before_activation: [1.2923401  1.39225678]
state： [0.85973818 0.88366641]
final_output [2.72707101]


In [4]:
np.dot(np.array([1.0,2.0]) , np.array([[1.0, 2.0],[1.0, 2.0]]))

array([3., 6.])

In [5]:
np.array([1.0,2.0]).dot(np.array([[1.0, 2.0],[1.0, 2.0]]))

array([3., 6.])

In [6]:
1 * np.array([1.0, 2.0])

array([1., 2.])