## tf准备知识

In [26]:
import tensorflow as tf

c = tf.constant("hello")
with tf.Session() as sess:
    print(sess.run(c))

b'hello'


In [30]:
var = tf.Variable(tf.random_uniform([2,3]), name="VAR")
INIT = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(INIT)
    print(sess.run(var))
    print(var)
    for i in tf.global_variables():
        print(i)

[[0.54363596 0.34734452 0.9040042 ]
 [0.23754036 0.7584441  0.6593758 ]]
<tf.Variable 'VAR_3:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'layer/weights/Variable:0' shape=(1, 10) dtype=float32_ref>
<tf.Variable 'layer_1/weights/Variable:0' shape=(1, 10) dtype=float32_ref>
<tf.Variable 'layer_2/weights/W:0' shape=(1, 10) dtype=float32_ref>
<tf.Variable 'layer_2/biases/b:0' shape=(1, 10) dtype=float32_ref>
<tf.Variable 'layer_3/weights/W:0' shape=(10, 1) dtype=float32_ref>
<tf.Variable 'layer_3/biases/b:0' shape=(1, 1) dtype=float32_ref>
<tf.Variable 'input2:0' shape=(3,) dtype=float32_ref>
<tf.Variable 'VAR:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'VAR_1:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'VAR_2:0' shape=(2, 3) dtype=float32_ref>
<tf.Variable 'VAR_3:0' shape=(2, 3) dtype=float32_ref>


In [31]:
tf.reset_default_graph()
tf.global_variables()

[]

### tf.Graph()创建新的计算图

In [36]:
import tensorflow as tf
# 加载库会创建默认的Graph对象
# 再默认图中添加一个节点
a = tf.constant(1, name="a")

# 创建一个新的计算图
g = tf.Graph()
with g.as_default():
    b = tf.constant([1,2], name="b")

# 在默认的数据流图中
c = tf.constant([3,4], name="c")

sess = tf.Session()
print(sess.run(a))
print(sess.run(c))

1
[3 4]


In [37]:
sess = tf.Session(graph=g)
print(sess.run(b))

[1 2]


### 常量节点 constant

In [41]:
a = tf.constant(5)
b = tf.constant(7)
node_add = tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(node_add))

12


### 占位符节点 placeholder

In [43]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
node_add = tf.add(a,b)
with tf.Session() as sess:
    print(sess.run(node_add, feed_dict={a:5, b:7}))
    print(sess.run(node_add, feed_dict={a:[2,0], b:[1,8]}))

12.0
[3. 8.]


### 变量节点 variable

In [44]:
a = tf.Variable(5, tf.float32) # 可动态修改
b = tf.Variable(7, tf.float32)
node_add = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(node_add))
    
    new_a = tf.assign(a, 9)
    sess.run(new_a)
    print(sess.run(node_add))

12
16


In [46]:
zeros = tf.zeros([2,2])
ones = tf.ones([6])
uniform = tf.random_uniform([3,3,3], minval=0, maxval=10)
normal = tf.random_normal([3,3,3], mean=0, stddev=2.0)
trunc = tf.truncated_normal([2,2], mean=5.0, stddev=1.0)
random_var = tf.Variable(tf.truncated_normal([2,2]))

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init) 

var1 = tf.Variable(0, name='init_1') 
init1 = tf.variables_initializer([var1], name="init_var1")
sess.run(init1)

In [47]:
not_trainable = tf.Variable(0, trainable=False)

In [57]:
v1 = tf.Variable([1])
v2 = tf.Variable(tf.random_normal([2,3], mean=1, stddev=2))
with tf.Session() as sess:   
    initialization = tf.global_variables_initializer()   
    sess.run(initialization) 
    print(sess.run(v1))
    print(v1.eval())
    print(sess.run(v2))
    print(v2.eval())

[1]
[1]
[[ 1.9545484 -1.7139015  3.6554484]
 [ 1.0186687  2.6827338  4.1833076]]
[[ 1.9545484 -1.7139015  3.6554484]
 [ 1.0186687  2.6827338  4.1833076]]


In [58]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(v1.eval())
    
    assign = tf.assign(v1, [9])
    print(v1.eval())
    
    sess.run(assign)
    print(v1.eval())

[1]
[1]
[9]


### 操作节点 operation

In [60]:
a = tf.constant(5) 
b = tf.constant(7) 
node_add = tf.multiply(a, b) 
with tf.Session() as sess:
    print(sess.run(node_add))

35


### 会话 session

In [62]:
a = tf.Variable(5, tf.float32) 
b = tf.Variable(7, tf.float32) 
node_add = tf.add(a, b) 
with tf.Session() as sess:   
    initialization = tf.global_variables_initializer()   
    sess.run(initialization)   
    print(sess.run(node_add))

12


In [70]:
'''
    会报错：
    ValueError: Fetch argument <tf.Variable 'a:0' shape=(1,) dtype=int32_ref> cannot be interpreted as a Tensor. 
    (Tensor Tensor("a:0", shape=(1,), dtype=int32_ref) is not an element of this graph.)
'''
import tensorflow as tf 

with tf.Graph().as_default():
    g_a = tf.Variable([7], name="a")

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(g_a))

In [65]:
import tensorflow as tf 

with tf.Graph().as_default():
    g_a = tf.Variable([7], name="a")

    init = tf.global_variables_initializer()

    with tf.Session() as sess:
        sess.run(init)
        print(sess.run(g_a))

[7]


In [67]:
import tensorflow as tf 
graph = tf.Graph()
with graph.as_default():
    g_a = tf.Variable([7], name="a")

    init = tf.global_variables_initializer()

with tf.Session(graph=graph) as sess:
    sess.run(init)
    print(sess.run(g_a))

[7]


In [68]:
a = tf.Variable(5, tf.float32) 
b = tf.Variable(7, tf.float32) 
node_add = tf.add(a, b) 
sess = tf.InteractiveSession()
initialization = tf.global_variables_initializer()
initialization.run()
print(node_add.eval())

12


## //////////////////////////////////////////////////////////////////////

In [1]:
import tensorflow as tf
a = tf.constant([1.0, 2.0], name="a")
b = tf.constant([2.0, 3.0], name="b")
result = a+b

/home/wujiaocan/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
print(a.graph is tf.get_default_graph())

True


In [78]:
import tensorflow as tf

g1 = tf.Graph()
with g1.as_default():
    # 在计算图g1中定义变量“v"，并设置初始值为0.
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer)

g2 = tf.Graph()
with g2.as_default():
    # 在计算图g2中定义变量“v"，并设置初始值为1.
    v = tf.get_variable("v", shape=[1], initializer=tf.ones_initializer)

# 在计算图g1中读取变量"v"的取值
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

# 在计算图g2中读取变量"v"的取值
with tf.Session(graph=g2) as sess:
    sess.run(tf.global_variables_initializer())
    with tf.variable_scope("", reuse=True):
        print(sess.run(tf.get_variable("v")))

[0.]
[1.]


In [79]:
weights = tf.Variable(tf.random_normal([2,3], stddev=2)) # 没指定均值，默认为0

In [80]:
bias = tf.Variable(tf.zeros([3]))

In [ ]:
w2 = tf.Variable(weights.initial_value())        # w2的值与weights相同
w3 = tf.Variable(weights.initial_value() * 2.0)  # w3的值为weights的二倍

### 向前传播

In [88]:
import tensorflow as tf

w1 = tf.Variable(tf.random_normal((2,3), stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal((3,1), stddev=1, seed=1))

# x = tf.constant([[0.7, 0.9]])   # 1x2矩阵
# x = tf.placeholder(tf.float32, shape=(1,2), name="input")
x = tf.placeholder(tf.float32, shape=(3,2), name="input")

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

# tf.clip_by_value(A, min, max)：输入一个张量A，把A中的每一个元素的值都压缩在min和max之间。
# 小于min的让它等于min，大于max的元素的值等于max。
y = tf.sigmoid(y)
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))
                               + (1-y_) * tf.log(tf.clip_by_value(1-y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)

sess = tf.Session()

sess.run(tf.global_variables_initializer())
# 等价下面分别初始化两个变量
# sess.run(w1.initializer)
# sess.run(w2.initializer)

# print(sess.run(y))
print(sess.run(y, feed_dict={x: [[0.7, 0.9], [0.1, 0.4], [0.5, 0.8]]}))
sess.close()

[[3.957578 ]
 [1.1537654]
 [3.1674924]]


### 完整神经网络

In [89]:
import tensorflow as tf
from numpy.random import RandomState

In [90]:
# 定义神经网络的参数，输入和输出节点。
batch_size = 8
w1= tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2= tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_= tf.placeholder(tf.float32, shape=(None, 1), name='y-input')

In [147]:
#  定义前向传播过程，损失函数及反向传播算法。
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)
y = tf.sigmoid(y)
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0))    
                                + (1 - y_) * tf.log(tf.clip_by_value(1 - y, 1e-10, 1.0)))# 做平滑，有可能y很接近0

# cross_entropy = -tf.reduce_mean(y_ * tf.log(y)
#                                 + (1 - y_) * tf.log(1 - y))

train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [145]:
# 生成模拟数据集。
rdm = RandomState(1)
X = rdm.rand(128,2)  # 128 x 2
# Y = [int(x1+x2 < 1) for (x1, x2) in X] # 一维
Y = [[int(x1+x2 < 1)] for (x1, x2) in X] # 二维

In [148]:
# 创建一个会话来运行TensorFlow程序
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    
    # 输出目前（未经训练）的参数取值
    print(sess.run(w1))
    print(sess.run(w2))
    print("\n")
    
    # 训练模型
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128 # batch_size=8
        end = (i*batch_size) % 128 + batch_size
#         sess.run([train_step, y, y_], feed_dict={x: X[start:end], y_: Y[start:end]})
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})

        if i % 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x: X, y_: Y})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
    
    # 输出训练后的参数取值。
    print("\n")
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]


After 0 training step(s), cross entropy on all data is 1.89805
After 1000 training step(s), cross entropy on all data is 0.655075
After 2000 training step(s), cross entropy on all data is 0.626172
After 3000 training step(s), cross entropy on all data is 0.615096
After 4000 training step(s), cross entropy on all data is 0.610309


[[ 0.02476983  0.56948674  1.6921941 ]
 [-2.1977348  -0.23668921  1.1143895 ]]
[[-0.45544702]
 [ 0.49110925]
 [-0.98110336]]


In [150]:
import tensorflow as tf

In [151]:
w1 = tf.Variable(tf.random_normal([2,3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3,1], stddev=1, seed=1))
x = tf.placeholder(tf.float32 ,shape=(None, 2), name="x-input")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y-input")

In [158]:
a = tf.matmul(x, w1)
y = tf.matmul(a, w2)
y = tf.sigmoid(y)

cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1))
                              + (1-y_)*tf.log(tf.clip_by_value((1-y), 1e-10, 1)))

train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [154]:
import numpy
X = numpy.random.RandomState(2).rand(128,2)
Y = [[int(x1+x2 < 1)] for x1, x2 in X]

In [159]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(w1))
    print(sess.run(w2))
    print("\n")
    
    STEPS=5000
    batch_size=8
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        
        if i % 1000 == 0:
            print(sess.run(cross_entropy, feed_dict={x:X, y_:Y}))
    print("\n")
    print(sess.run(w1))
    print(sess.run(w2))

[[-0.8113182   1.4845988   0.06532937]
 [-2.4427042   0.0992484   0.5912243 ]]
[[-0.8113182 ]
 [ 1.4845988 ]
 [ 0.06532937]]


1.6847135
0.6713028
0.6602192
0.65981317
0.65962255


[[-0.24938132  0.82057744  1.1775366 ]
 [-2.0232887  -0.38369426  1.3972882 ]]
[[-0.2917295]
 [ 0.8541243]
 [-0.8009632]]
